apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-414-1739289874
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: cf674d3d0ffc95a9cf045b5e9c02b48fd550cb76
    konflux-release-data/ocp-version: ocp-414
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-414
  components:
    - name: rhoai-fbc-fragment-ocp-414
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:d5c0abd9b7ec45f1d3beebf016c5508a70868829d386b145235093ce5d57b155
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: dcb50f38d1b6739d6c5223a5951d2f40e3912054