apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1738073482
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: d8f5ef3e5c423a3cccd5eeb2dee9136a079cef05
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:ce707d0989a7e5bd622c9cce33d834724123a1514111f0ecf566bd953bcaca8e
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: ad8faee6bef0a941f1cdbaeed9cbc00e16fcf3b1