apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: rhoai-fbc-fragment-ocp-419-1738580105
  namespace: rhoai-tenant
  labels:
    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: 89f83898ae0d8d38c98f6ef0487548ebd126f307
    konflux-release-data/ocp-version: ocp-419
    konflux-release-data/artifact-type: fbc
spec:
  application: rhoai-fbc-fragment-ocp-419
  components:
    - name: rhoai-fbc-fragment-ocp-419
      containerImage: quay.io/rhoai/rhoai-fbc-fragment@sha256:ebb6ae74bb380fef72c86cbd4e472d307c6400643918f39c76f36ba8b4932911
      source:
        git:
          url: https://github.com/red-hat-data-services/RHOAI-Build-Config
          revision: 0c41ffa799f41a90e8a2237e2eb00def061e05fe