apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  labels:
    konflux-release-data/artifact-type: components
    konflux-release-data/rbc-release-commit: cf674d3d0ffc95a9cf045b5e9c02b48fd550cb76
    test.appstudio.openshift.io/type: override
  name: rhoai-v2-17-1739283636
  namespace: rhoai-tenant
spec:
  application: rhoai-v2-17
  components:
  - containerImage: quay.io/rhoai/odh-operator-bundle@sha256:8894db3352d2c8e666bbd0b93ae36474f6d2dcf1e59c24328de8a95667a45bb0
    name: odh-operator-bundle-v2-17
    source:
      git:
        revision: 23f912c85ec3e8a020054a3825c25001d4070926
        url: https://github.com/red-hat-data-services/RHOAI-Build-Config
  - containerImage: quay.io/rhoai/odh-codeflare-operator-rhel8@sha256:fc6d4c739d6e71fd613aa5ba0821035f0a8e783ea94a411abb82b26a5d79406d
    name: odh-codeflare-operator-v2-17
    source:
      git:
        revision: dd9534b3b05b0a5a57fff7e4ef6f1681ed8d9f86
        url: https://github.com/red-hat-data-services/codeflare-operator
  - containerImage: quay.io/rhoai/odh-dashboard-rhel8@sha256:e19276083d932dad46be57674cadf2757a4eeb5d1e2cc2b4ae650e0c8d2c1b02
    name: odh-dashboard-v2-17
    source:
      git:
        revision: 39cbe30994691f130acc92c8de121e754d4519a0
        url: https://github.com/red-hat-data-services/odh-dashboard
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-argoexec-rhel8@sha256:d78353c90bfbdf943547d5f6e3f547ab02f47836ca2cbf3f101977685bf3e34c
    name: odh-data-science-pipelines-argo-argoexec-v2-17
    source:
      git:
        revision: c565e37683724cf212a49bb90dcc6b85346c46ff
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel8@sha256:5895e8a111dcd34e6cfec5ce9f84430164b4f6ee43daf8029d0c3b7eeffdd25c
    name: odh-data-science-pipelines-argo-workflowcontroller-v2-17
    source:
      git:
        revision: c565e37683724cf212a49bb90dcc6b85346c46ff
        url: https://github.com/red-hat-data-services/argo-workflows
  - containerImage: quay.io/rhoai/odh-data-science-pipelines-operator-controller-rhel8@sha256:913162d37998b5f5503ea9a6acdd32a03fe1588658ed481027c381feaa298542
    name: odh-data-science-pipelines-operator-controller-v2-17
    source:
      git:
        revision: 4c8a0fe77b98123c166cf2fb563e351865d82e39
        url: https://github.com/red-hat-data-services/data-science-pipelines-operator
  - containerImage: quay.io/rhoai/odh-kf-notebook-controller-rhel8@sha256:0b105c6231945f7907424520f53df8ae5cfec9e4dd8fe8894928851e06729917
    name: odh-kf-notebook-controller-v2-17
    source:
      git:
        revision: 517352b5e23efad07ebdc9614d7a567538bb2346
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-kuberay-operator-controller-rhel8@sha256:ba1d528589d4ea5288cdb424a84caf2e2ac394105f3343d8cbff299e2f1fb012
    name: odh-kuberay-operator-controller-v2-17
    source:
      git:
        revision: 13e748292993b6c2e1d566bfda451ca6aa22ad72
        url: https://github.com/red-hat-data-services/kuberay
  - containerImage: quay.io/rhoai/odh-kueue-controller-rhel8@sha256:849977d802846fceb0b642c28db3611a88163b6025de36695205d81162935497
    name: odh-kueue-controller-v2-17
    source:
      git:
        revision: f5490d4556693b86d2eaa6d5971742ff3b8413ac
        url: https://github.com/red-hat-data-services/kueue
  - containerImage: quay.io/rhoai/odh-ml-pipelines-api-server-v2-rhel8@sha256:85b991f09d439ca1e1df6b490097f587a76a2aaf94cb98f360e513f0d153483a
    name: odh-ml-pipelines-api-server-v2-v2-17
    source:
      git:
        revision: 6010386d43bffaba74cdbde94d72e9c45d5a1f83
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-driver-rhel8@sha256:8c3b9c8d8303f45766dea82194cf0d886eeb74bf9055c5aae06c8e78f8d28b04
    name: odh-ml-pipelines-driver-v2-17
    source:
      git:
        revision: 6010386d43bffaba74cdbde94d72e9c45d5a1f83
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-launcher-rhel8@sha256:83c2d8f4f66835bd22cfd29f4ae9b57bfacf16393b5080fbbe3057cab90dfdda
    name: odh-ml-pipelines-launcher-v2-17
    source:
      git:
        revision: 6010386d43bffaba74cdbde94d72e9c45d5a1f83
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-persistenceagent-v2-rhel8@sha256:b94552aa082251c6c7b85d49cd3444a12149b8825473619517fa3edbd1748195
    name: odh-ml-pipelines-persistenceagent-v2-v2-17
    source:
      git:
        revision: 6010386d43bffaba74cdbde94d72e9c45d5a1f83
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel8@sha256:5979ff12a1b4b96b307ffc601388c195a5ce49bf53c85b7a9e7da20f6266ff8d
    name: odh-ml-pipelines-scheduledworkflow-v2-v2-17
    source:
      git:
        revision: 6010386d43bffaba74cdbde94d72e9c45d5a1f83
        url: https://github.com/red-hat-data-services/data-science-pipelines
  - containerImage: quay.io/rhoai/odh-mlmd-grpc-server-rhel8@sha256:f9a98109664adec37649f616f63e86605df2feb6fb9178b37ddeba59f6460930
    name: odh-mlmd-grpc-server-v2-17
    source:
      git:
        revision: 1cb9b5215dca8c1c8bd27876f56f7c8c6847213a
        url: https://github.com/red-hat-data-services/ml-metadata
  - containerImage: quay.io/rhoai/odh-mm-rest-proxy-rhel8@sha256:c2995df85c0023ebc43e9dc30a258323353387450af99295fd67b57fb8afc36b
    name: odh-mm-rest-proxy-v2-17
    source:
      git:
        revision: 2e78fae1c2efc423572e583c06270985154845e4
        url: https://github.com/red-hat-data-services/rest-proxy
  - containerImage: quay.io/rhoai/odh-model-controller-rhel8@sha256:f581ada86bbf09e794c9ae100197a7dda618ca1efc344281839801609123902f
    name: odh-model-controller-v2-17
    source:
      git:
        revision: 14bed0432633e78f4cbfcc3caf908fa0ac43709f
        url: https://github.com/red-hat-data-services/odh-model-controller
  - containerImage: quay.io/rhoai/odh-model-registry-operator-rhel8@sha256:47653dc36a82d1b00f10d03df92aa836be8111c381cdb9caabd3a68829f6d683
    name: odh-model-registry-operator-v2-17
    source:
      git:
        revision: 6548b4d49d4906fbe333a847d0c50d263a77ddd8
        url: https://github.com/red-hat-data-services/model-registry-operator
  - containerImage: quay.io/rhoai/odh-model-registry-rhel8@sha256:713025cc0357b2052bec976eb74f2e0ec14c1ea4426c1f1eb78a6331973db7a7
    name: odh-model-registry-v2-17
    source:
      git:
        revision: ad7639730b1afe783cbdc1a417ab6efbd282c434
        url: https://github.com/red-hat-data-services/model-registry
  - containerImage: quay.io/rhoai/odh-modelmesh-rhel8@sha256:58fc4ea5fcabd64c061a4f30259b354ffbcbb8c16ffc442f47404ddd49ffd3c9
    name: odh-modelmesh-v2-17
    source:
      git:
        revision: 0a3e07b55125b80b534d2cc34c327c0c475fe41d
        url: https://github.com/red-hat-data-services/modelmesh
  - containerImage: quay.io/rhoai/odh-modelmesh-runtime-adapter-rhel8@sha256:78e18816a15b2d744a76710523a574f483606646d5e661b58a1d8562dc85526f
    name: odh-modelmesh-runtime-adapter-v2-17
    source:
      git:
        revision: f143ecf973243dc3d3c7dc44125051ff100844f4
        url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter
  - containerImage: quay.io/rhoai/odh-modelmesh-serving-controller-rhel8@sha256:d846107b3580c8ec623bf7cb131236990d20df91ee5c4b2c53474d18e0e112a1
    name: odh-modelmesh-serving-controller-v2-17
    source:
      git:
        revision: 714a7b0b83a250686a5eb805fcf5b812e35f3fea
        url: https://github.com/red-hat-data-services/modelmesh-serving.git
  - containerImage: quay.io/rhoai/odh-notebook-controller-rhel8@sha256:58516cc6ece1c6bfb6c426006b2820333c8be181f7e16471b24f52cb024df6b3
    name: odh-notebook-controller-v2-17
    source:
      git:
        revision: 517352b5e23efad07ebdc9614d7a567538bb2346
        url: https://github.com/red-hat-data-services/kubeflow
  - containerImage: quay.io/rhoai/odh-rhel8-operator@sha256:73330b67b6b104e67468463f2de1b029530793fc2df550c70851e6a3575e6307
    name: odh-operator-v2-17
    source:
      git:
        revision: 1920299c23f12cee66824f92bbce71bd3d97f5f4
        url: https://github.com/red-hat-data-services/rhods-operator
  - containerImage: quay.io/rhoai/odh-training-operator-rhel8@sha256:3e6c0ff6036b1feedfae2ddbc287e8dee1ee7f8e69ca7e0b911f77c929c50e53
    name: odh-training-operator-v2-17
    source:
      git:
        revision: 8229a81b9a1fab813639a1ed2a013dd7c6021a97
        url: https://github.com/red-hat-data-services/training-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-operator-rhel8@sha256:cdf0176ce6a2425ed485e188ae25c83b1accbceed515c426c6101a014b43d837
    name: odh-trustyai-service-operator-v2-17
    source:
      git:
        revision: ac7d3b32e3bb2230834abe23245d753ec0c6415e
        url: https://github.com/red-hat-data-services/trustyai-service-operator
  - containerImage: quay.io/rhoai/odh-trustyai-service-rhel8@sha256:9f5c7f682c534d3d07daceaef8c49c7d03d489f160b0adccdb296c5b9f67b748
    name: odh-trustyai-service-v2-17
    source:
      git:
        revision: 192fc91296bf4f10481b6c513c8febc83db5ef0b
        url: https://github.com/red-hat-data-services/trustyai-explainability
